### ISSUE TITLE
Input processing

### ISSUE THREAD

**Issue by mirabilos** [Natureshadow/MirWTFApp#10]
Severity: normal

Input processing must be synchronised with the other wtf implementations, as it’s part of the DB API. This means:

If the search term (after uppercasing) matches /[A-Z]\./ then all dots are removed from the term. This is not currently given (search for “o.m.g.” returns nothing). Beware: “-.” as term does NOT match this, and this the dot MUST be retained.

Uppercasing rules: Only [a-zäöüßñáéíóçè] are upper-cased; other than U+0009 (tab) and U+000A (newline), any other UTF-8 encoded Unicode codepoint is a valid search term. (Not tested whether the app conforms.)

**Comment by Natureshadow** [comment]
I'm not quite sure how this is meant.

What you say: The expression you gave matches "any letter followed by any single character" anchored anywhere in the string. But this also matches ".---A/foo", which does not seem to be your intention.

What I think: You want to match al lstrings that contain only letters and periods and no other characters.

Please correct me and.or explain further.

**Comment by mirabilos** [comment]
Dominik George dixit:

>What you say: The expression you gave matches "any letter followed by
>any single character" anchored anywhere in the string. But this also
>matches ".---A/foo", which does not seem to be your intention.

Huh? Did github eat the backslash?

I mean: any [A-Z] followed by a U+002E FULL STOP in the pattern,
anywhere, after uppercasing them, will cause all U+002E to be removed.
See mircvs://src/usr.bin/wtf/wtf or mircvs://www/files/wtf.cgi for
details on the algorithm used.

bye,
//mirabilos
-- 
“The final straw, to be honest, was probably my amazement at the volume of
petty, peevish whingeing certain of your peers are prone to dish out on
d-devel, telling each other how to talk more like a pretty princess, as though
they were performing some kind of public service.” (someone to me, privately)

**Comment by Natureshadow** [comment]
As discussed, please note the mapping rules for uppercasing in the acronyms file. I will then implement it.

**Comment by mirabilos** [comment]
Dominik George dixit:

>As discussed, please note the mapping rules for uppercasing in the
>acronyms file. I will then implement it.

Done and uploaded, including rsync for anoncvs:

• src/share/misc/acronyms,v now starts with case mapping line
• second line is version number (by accident, it's the line that
  starts with ' @(#)' but that probably will always be the second one)
• src/usr.bin/wtf/wtf,v already also implements the new casemapping
• www/files/{raw,wtf}.cgi,v don’t yet, as I can’t Perl

bye,
//mirabilos
-- 
>> Why don't you use JavaScript? I also don't like enabling JavaScript in
> Because I use lynx as browser.
+1
	-- Octavio Alvarez, me and ⡍⠁⠗⠊⠕ (Mario Lang) on debian-devel
