### ISSUE TITLE
Crash after 3rd "miau"

### ISSUE THREAD

**Issue by sbruder** [Natureshadow/MirWTFApp#23]
If I type in "miau"  three times the app crashes.

**Comment by Natureshadow** [comment]
Plesse provide a stack trace for the crash!

**Comment by sbruder** [comment]
I/Timeline( 2649): Timeline: Activity_launch_request id:de.naturalnet.mirwtfapp time:254369004
I/ActivityManager( 2248): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.naturalnet.mirwtfapp/.MainActivity} from pid 2649
I/ActivityManager( 2248): Start proc de.naturalnet.mirwtfapp for activity de.naturalnet.mirwtfapp/.MainActivity: pid=8150 uid=10242 gids={50242, 3003}
D/ActivityThread( 8150): handleBindApplication:de.naturalnet.mirwtfapp
I/ActivityManager( 2248): Displayed de.naturalnet.mirwtfapp/.MainActivity: +1s318ms
I/Timeline( 2248): Timeline: Activity_windows_visible id: ActivityRecord{42c538b8 u0 de.naturalnet.mirwtfapp/.MainActivity t93} time:254370480
I/dalvikvm( 8150):   at de.naturalnet.mirwtfapp.MainActivity.doWTFSearch(MainActivity.java:402)
I/dalvikvm( 8150):   at de.naturalnet.mirwtfapp.MainActivity.access$000(MainActivity.java:65)
I/dalvikvm( 8150):   at de.naturalnet.mirwtfapp.MainActivity$2.onEditorAction(MainActivity.java:267)
E/AndroidRuntime( 8150): Process: de.naturalnet.mirwtfapp, PID: 8150
E/AndroidRuntime( 8150): 	at de.naturalnet.mirwtfapp.MainActivity.doWTFSearch(MainActivity.java:402)
E/AndroidRuntime( 8150): 	at de.naturalnet.mirwtfapp.MainActivity.access$000(MainActivity.java:65)
E/AndroidRuntime( 8150): 	at de.naturalnet.mirwtfapp.MainActivity$2.onEditorAction(MainActivity.java:267)
W/ActivityManager( 2248):   Force finishing activity de.naturalnet.mirwtfapp/.MainActivity
W/ActivityManager( 2248): Activity pause timeout for ActivityRecord{42c538b8 u0 de.naturalnet.mirwtfapp/.MainActivity t93 f}
W/ActivityManager( 2248): Activity destroy timeout for ActivityRecord{42c538b8 u0 de.naturalnet.mirwtfapp/.MainActivity t93 f}

**Comment by Natureshadow** [comment]
I can see no crash whatsoever in this log…

**Comment by sbruder** [comment]
I/dalvikvm-heap( 9440): Forcing collection of SoftReferences for 39674896-byte allocation
E/dalvikvm-heap( 9440): Out of memory on a 39674896-byte allocation.
I/dalvikvm( 9440): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm( 9440):   | group="main" sCount=0 dsCount=0 obj=0x4181bde0 self=0x4180a400
I/dalvikvm( 9440):   | sysTid=9440 nice=0 sched=0/0 cgrp=apps handle=1074815316
I/dalvikvm( 9440):   | state=R schedstat=( 2815921584 1665058336 4099 ) utm=231 stm=50 core=0
I/dalvikvm( 9440):   at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
I/dalvikvm( 9440):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
I/dalvikvm( 9440):   at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
I/dalvikvm( 9440):   at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
I/dalvikvm( 9440):   at android.content.res.Resources.loadDrawable(Resources.java:2249)
I/dalvikvm( 9440):   at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
I/dalvikvm( 9440):   at android.widget.ImageView.<init>(ImageView.java:129)
I/dalvikvm( 9440):   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
I/dalvikvm( 9440):   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
I/dalvikvm( 9440):   at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
I/dalvikvm( 9440):   at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
I/dalvikvm( 9440):   at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
I/dalvikvm( 9440):   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
I/dalvikvm( 9440):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
I/dalvikvm( 9440):   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
I/dalvikvm( 9440):   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
I/dalvikvm( 9440):   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
I/dalvikvm( 9440):   at de.naturalnet.mirwtfapp.MainActivity.doWTFSearch(MainActivity.java:402)
I/dalvikvm( 9440):   at de.naturalnet.mirwtfapp.MainActivity.access$000(MainActivity.java:65)
I/dalvikvm( 9440):   at de.naturalnet.mirwtfapp.MainActivity$2.onEditorAction(MainActivity.java:267)
I/ActivityManager( 2248): Process com.csipsimple (pid 8771) has died.
I/ActivityManager( 2248): Process de.danoeh.antennapod (pid 8829) has died.
I/dalvikvm( 9440):   at android.widget.TextView.onEditorAction(TextView.java:4236)
I/ActivityManager( 2248): Process com.cyanogenmod.lockclock (pid 8077) has died.
I/dalvikvm( 9440):   at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
I/dalvikvm( 9440):   at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
I/dalvikvm( 9440):   at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
I/dalvikvm( 9440):   at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm( 9440):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm( 9440):   at android.app.ActivityThread.main(ActivityThread.java:5146)
I/dalvikvm( 9440):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm( 9440):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm( 9440):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
I/dalvikvm( 9440):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
I/dalvikvm( 9440):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 9440): 
D/skia    ( 9440): --- allocation failed for scaled bitmap
D/AndroidRuntime( 9440): Shutting down VM
W/dalvikvm( 9440): threadid=1: thread exiting with uncaught exception (group=0x4181ace0)
E/AndroidRuntime( 9440): FATAL EXCEPTION: main
E/AndroidRuntime( 9440): Process: de.naturalnet.mirwtfapp, PID: 9440
E/AndroidRuntime( 9440): java.lang.OutOfMemoryError
E/AndroidRuntime( 9440): 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
E/AndroidRuntime( 9440): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
E/AndroidRuntime( 9440): 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
E/AndroidRuntime( 9440): 	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
E/AndroidRuntime( 9440): 	at android.content.res.Resources.loadDrawable(Resources.java:2249)
E/AndroidRuntime( 9440): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
E/AndroidRuntime( 9440): 	at android.widget.ImageView.<init>(ImageView.java:129)
E/AndroidRuntime( 9440): 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
E/AndroidRuntime( 9440): 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
E/AndroidRuntime( 9440): 	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
E/AndroidRuntime( 9440): 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
E/AndroidRuntime( 9440): 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
E/AndroidRuntime( 9440): 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/AndroidRuntime( 9440): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime( 9440): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 9440): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 9440): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 9440): 	at de.naturalnet.mirwtfapp.MainActivity.doWTFSearch(MainActivity.java:402)
E/AndroidRuntime( 9440): 	at de.naturalnet.mirwtfapp.MainActivity.access$000(MainActivity.java:65)
E/AndroidRuntime( 9440): 	at de.naturalnet.mirwtfapp.MainActivity$2.onEditorAction(MainActivity.java:267)
E/AndroidRuntime( 9440): 	at android.widget.TextView.onEditorAction(TextView.java:4236)
E/AndroidRuntime( 9440): 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
E/AndroidRuntime( 9440): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
E/AndroidRuntime( 9440): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
E/AndroidRuntime( 9440): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9440): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 9440): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime( 9440): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9440): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 9440): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime( 9440): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime( 9440): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2248):   Force finishing activity de.naturalnet.mirwtfapp/.MainActivity
E/rsC++   ( 2649): RS Message thread exiting.
D/lights  ( 2248): set_light_buttons: 2
W/ActivityManager( 2248): Activity pause timeout for ActivityRecord{421f3628 u0 de.naturalnet.mirwtfapp/.MainActivity t96 f}
E/        ( 2649): Device driver API match
E/        ( 2649): Device driver API version: 23
E/        ( 2649): User space API version: 23 
E/        ( 2649): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Wed Oct  9 21:05:57 KST 2013 
V/RenderScript( 2649): 0x54653958 Launching thread(s), CPUs 2
I/Timeline( 2649): Timeline: Activity_idle id: android.os.BinderProxy@41c6e590 time:254883304
I/Timeline( 2248): Timeline: Activity_windows_visible id: ActivityRecord{41db3128 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:254883739

**Comment by mirabilos** [comment]
possibly related: http://stackoverflow.com/q/36897990/2171120

**Comment by mirabilos** [comment]
Got this link at SO: http://developer.android.com/training/displaying-bitmaps/load-bitmap.html

It strongly suggests to make `inSampleSize` a power of two instead of what you committed.

**Comment by Natureshadow** [comment]
@mirabilos I actually tried that first. It first failed because the height of the ImageView is 0 before adding the image. Removing the height part yielded an iss of 1 for the emulator, because it has 810px in width and 1440/2<810. It did not fix the issue. The commited code actually does.
