### ISSUE TITLE
Reverse normalisation

### ISSUE THREAD

**Issue by Natureshadow** [Natureshadow/MirWTFApp#28]
@mirabilos

Should normalisation also happen in reverse direction, at least for auto completion? E.g. NFF should also yield NF/F?

**Comment by mirabilos** [comment]
Normalisation does not delete or insert slashes. NFF should not match any expansion for NF/F, nor should NF/F match any expansion for NFF.

More background: Normalisation is also applied when creating the acronyms file (“make check” in /usr/src/share/misc/ on MirBSD), so a reverse direction cannot exist unless the data is malformed.

**Comment by Natureshadow** [comment]
@mirabilos So, in order to find out what NF/F means, I absolutely do need to know it is spelled exactly NF/F?

**Comment by mirabilos** [comment]
Dominik George dixit:

>@mirabilos So, in order to find out what NF/F means, I absolutely do
>need to know it is spelled exactly NF/F?

Precisely. That’s why we have some forwarding in action for cases
where the extra punctuation is optional, such as:

SMIME	(cf. S/MIME)

In the general case, this is not needed, though – for example, c/o
(as used in postal addresses) is never spelt without it, and in case
of doubt, only the entry *without* punctuation is added to the database.

**Comment by Natureshadow** [comment]
Alright!
