### ISSUE TITLE
Input field and cursor colours

### ISSUE THREAD

**Issue by mirabilos** [Natureshadow/MirWTFApp#5]
Severity: wishlist

The cursor should not have colour (i.e. be black). The input field could be green like the silhouette dæmon, maybe?

**Comment by Natureshadow** [comment]
This will be done in a complete UI redesign in the future.

**Comment by Natureshadow** [comment]
I am wondering whether this would make an all-dark theme necessary to create the desired colour scheme.

I don't want to impose a dark theme on users, and I think multiple themes are overkill in the app.

I basically want the app to stick with the device theme. Do you think only changing the input field colour would be sufficient, even on a potentially light background?

**Comment by mirabilos** [comment]
Hm, I have no idea what’s possible etc. but a pink cursor is annoying.
For the rest, I’d probably have to see them…

**Comment by Natureshadow** [comment]
OK, I think there are two possibilities:

a) make the action bar and the input field a green taken from the logo and leave the rest untouched
b) re-style the entire app in a dark MirBSD theme

I think we'll need to try both.

**Comment by Natureshadow** [comment]
Incomplete.
